# -*- coding: utf-8 -*-
"""Problema 1 Modelacion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CEgzwPmSSWNcLo_QkNj7DHxpXsotmwYm
"""

import random

def problem_modelacion():
#Definimos nuestras variables
  #Selección de nombres
  nombres_1 = ["Juan", "Maria", "Pablo", "Rosa", "Jose", "Sofia", "Alejandro", "Valentina"]
  nom1 = random.choice(nombres_1)
  nombres_2 = ["Diego", "Fernanda", "Rivelino", "Nathalia", "Luis", "Karla", "Gael"]
  nom2 = random.choice(nombres_2)
  #Selección de relación entre el dinero de cada persona
  op = ["la mitad", "el doble", "el triple"]
  rel = random.choice(op)
  #Selección de cantidades
  if rel == "la mitad":
    a = 3*(random.randint(25, 35))
    b = 3*(random.randint(5, 8))
    c = (a + b)
    e = int(c/3)
    d = int(2*e)
    f = int(e-b)

  if rel == "el doble":
    a = 3*(random.randint(25, 35))
    b = 3*(random.randint(5, 8))
    c = (a + b)
    d = int(c/3)
    e = int(2*d)
    f = int(e-b)

  if rel == "el triple":
    a = 4*(random.randint(20, 30))
    b = 4*(random.randint(5, 8))
    c = (a + b)
    d = int(c/4)
    e = int(3*d)
    f = int(e-b)


#Planteamiento del problema
  print(f"{nom1} y {nom2} tienen ${a} pesos en conjunto; si al dinero de {nom2} se le sumaran ${b} pesos, entonces {nom2} tendría {rel} del dinero de {nom1}.")
  print(f"¿Cuánto dinero tienen {nom1} y {nom2} respectivamente?")

#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

#Planteamos las opciones de respuesta
  #Numeros en los que van a variar las respuestas
  r1 = random.choice([i for i in range(0,4)])

  r2 = random.choice([i for i in range(0,4) if i not in [r1]])

  r3 = random.choice([i for i in range(0,4) if i not in [r1, r2]])

  r4 = random.choice([i for i in range(0,4) if i not in [r1, r2, r3]])

  #Impresión de las respuestas modificadas
  print(f"\n a){nom1} tiene ${d - r1} pesos y {nom2} tiene ${f + r1} pesos.")
  print(f"\n b){nom1} tiene ${d + r2} pesos y {nom2} tiene ${f - r2} pesos.")
  print(f"\n c){nom1} tiene ${d - r3} pesos y {nom2} tiene ${f + r3} pesos.")
  print(f"\n d){nom1} tiene ${d + r4} pesos y {nom2} tiene ${f - r4} pesos.")
  print("\n e)Ninguna de las anteriores.")

#Petición de la respuesta al usuario
  resp = input("\nCual es la respuesta? ")

  if resp == "a":
    if r1 == 0:
      print("Correcto")
    else:
      print("Incorrecto")

  if resp == "b":
    if r2 == 0:
      print("Correcto")
    else:
      print("Incorrecto")

  if resp == "c":
    if r3 == 0:
      print("Correcto")
    else:
      print("Incorrecto")

  if resp == "d":
    if r4 == 0:
      print("Correcto")
    else:
      print("Incorrecto")

  if resp == "e":
    print("Incorrecto")

  if resp != "a" and resp != "b" and resp != "c" and resp != "d" and resp != "e":
    print("Respuesta no válida")


#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=


#Definimos condiciones para dar la solución
  s = input("\nDesea conocer la solución? 1 = si, 2 = no\n")
  if s == "1":

  #Solución
    print("\nSolución:")
    print(f"Si {nom2} tuviera ${b} pesos más, el dinero de {nom1} y {nom2} sumarian ${c} pesos en total.")

  #Soluciones especificas dependiendo el problema
    if rel == "la mitad":
      print(f"El dinero se debe dividir en tres partes iguales de donde {nom1} tendrá dos de ellas y {nom2} la otra.")
    if rel == "el doble":
      print(f"El dinero se debe dividir en tres partes iguales de donde {nom1} tendrá una de ellas y {nom2} las otras dos.")
    if rel == "el triple":
      print(f"El dinero se debe dividir en cuatro partes iguales de donde {nom1} tendrá una de ellas y {nom2} las otras tres.")

  #Solución
    print(f"Dejando así que {nom1} tiene ${d} pesos y {nom2} tiene ${e} pesos.")
    print(f"Sin embargo, esto es dentro de la situación hipotetica de que {nom2} tiene ${b} pesos más, por lo que en realidad {nom2} tiene ${f} pesos.")

  #Respuesta
    print(f"\n\nRespuesta: {nom1} tiene ${d} pesos y {nom2} tiene ${f} pesos.")

  else:
    print(" ")

#Problema 1.
problem_modelacion()